# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-13 22:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_auto_20170120_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporte_mensual',
            name='adjunto_exel',
            field=models.FileField(upload_to='Informe/'),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='supervisor',
            field=models.CharField(choices=[('Julio Prado', 'Julio Prado '), ('Maria del Carmen', 'Maria del Carmen'), ('Janeth Patricia', 'Janeth Patricia'), ('No tiene', 'No tiene')], default='', max_length=50),
        ),
    ]
